services:
  mongodb:
    image: mongo:6.0.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   container_name: linktutor-server
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - mongodb
  #   env_file:
  #     - ./server/.env
  #   restart: unless-stopped
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules

volumes:
  mongodb_data:
